document.addEventListener("DOMContentLoaded",()=>{gsap.registerPlugin(ScrollTrigger);const reduce=matchMedia("(prefers-reduced-motion:reduce)").matches;let lenis;if(!reduce&&window.Lenis){lenis=new Lenis({duration:1.15,smoothWheel:true,lerp:.075});lenis.on("scroll",ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0)}
const loader=document.querySelector(".loader"),bar=document.querySelector(".loadbar i"),pct=document.querySelector(".loader b"),o={v:0};gsap.to(o,{v:100,duration:1.8,ease:"power2.inOut",onUpdate:()=>pct.textContent=Math.round(o.v).toString().padStart(2,"0")+"%"});gsap.to(bar,{width:"100%",duration:1.8,ease:"power2.inOut"});gsap.to(loader,{yPercent:-100,delay:2,duration:.9,ease:"power4.inOut",onComplete:()=>loader.remove()});
gsap.to(".hero h1 b",{y:0,filter:"blur(0)",duration:1.1,delay:2.15,stagger:.11,ease:"power4.out"});gsap.from(".hero-label,.hero-info,.scroll",{y:25,opacity:0,duration:.7,delay:2.5,stagger:.1});
const cur=document.querySelector(".cursor");if(matchMedia("(pointer:fine)").matches&&!reduce){let x=innerWidth/2,y=innerHeight/2,cx=x,cy=y;addEventListener("mousemove",e=>{x=e.clientX;y=e.clientY});gsap.ticker.add(()=>{cx+=(x-cx)*.18;cy+=(y-cy)*.18;gsap.set(cur,{x:cx,y:cy})});document.querySelectorAll(".magnetic-area").forEach(e=>{e.onmouseenter=()=>cur.classList.add("view");e.onmouseleave=()=>cur.classList.remove("view")})}
document.querySelectorAll(".reveal").forEach(el=>gsap.to(el,{clipPath:"inset(0% 0% 0% 0%)",duration:1.2,ease:"power4.inOut",scrollTrigger:{trigger:el,start:"top 84%",once:true}}));
document.querySelectorAll(".pic").forEach(el=>{gsap.to(el,{clipPath:"inset(0% 0% 0% 0%)",duration:1.15,ease:"power4.inOut",scrollTrigger:{trigger:el,start:"top 84%",once:true}});gsap.to(el.querySelector("img"),{scale:1,duration:1.5,ease:"power4.out",scrollTrigger:{trigger:el,start:"top 84%",once:true}})});
if(!reduce){gsap.timeline({scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:1}}).to(".hero-copy",{y:-120,scale:.78,opacity:.15},0).to(".float.a",{scale:1.3,x:-80,rotation:-3},0).to(".float.b",{scale:1.3,x:90,opacity:0},0);if(innerWidth>900){const s=document.querySelector(".horizontal"),t=document.querySelector(".track"),d=()=>t.scrollWidth-innerWidth;gsap.to(t,{x:()=>-d(),ease:"none",scrollTrigger:{trigger:s,pin:true,scrub:1,end:()=>"+="+d(),invalidateOnRefresh:true}})}gsap.utils.toArray(".words div").forEach((e,i)=>gsap.fromTo(e,{x:i%2?100:-100,opacity:.2},{x:0,opacity:1,ease:"none",scrollTrigger:{trigger:".statement",start:"top 80%",end:"bottom 55%",scrub:1}}));gsap.to(".marquee div",{xPercent:-25,duration:18,repeat:-1,ease:"none"})}
document.querySelectorAll("[data-count]").forEach(el=>{let n={v:0},target=+el.dataset.count;ScrollTrigger.create({trigger:el,start:"top 88%",once:true,onEnter:()=>gsap.to(n,{v:target,duration:1.5,ease:"power2.out",onUpdate:()=>el.textContent=Math.round(n.v)})})});
const preview=document.querySelector(".service-preview"),pimg=preview.querySelector("img");document.querySelectorAll(".service").forEach(s=>{s.onmouseenter=()=>{if(innerWidth<=900)return;pimg.src=s.dataset.img;gsap.to(preview,{opacity:1,scale:1,duration:.4});};s.onmouseleave=()=>gsap.to(preview,{opacity:0,scale:.9,duration:.3})});
if(matchMedia("(pointer:fine)").matches&&!reduce)document.querySelectorAll(".magnetic").forEach(e=>{e.onmousemove=a=>{let r=e.getBoundingClientRect();gsap.to(e,{x:(a.clientX-r.left-r.width/2)*.15,y:(a.clientY-r.top-r.height/2)*.15,duration:.35})};e.onmouseleave=()=>gsap.to(e,{x:0,y:0,duration:.6,ease:"elastic.out(1,.4)"})});
const menu=document.querySelector(".mobile-menu");let open=false;document.querySelector(".menu").onclick=()=>{open=!open;gsap.to(menu,{yPercent:open?0:-100,autoAlpha:open?1:0,duration:.6,ease:"power4.inOut"});if(open)gsap.fromTo(".mobile-menu a",{y:60,opacity:0},{y:0,opacity:1,duration:.6,stagger:.08,delay:.15})};document.querySelectorAll(".mobile-menu a").forEach(a=>a.onclick=()=>{open=false;gsap.to(menu,{yPercent:-100,autoAlpha:0,duration:.5})});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.onclick=e=>{let t=document.querySelector(a.getAttribute("href"));if(!t)return;e.preventDefault();lenis?lenis.scrollTo(t,{offset:-30}):t.scrollIntoView({behavior:"smooth"})});document.querySelector("#top").onclick=()=>lenis?lenis.scrollTo(0):scrollTo({top:0,behavior:"smooth"});});
