document.addEventListener("DOMContentLoaded",()=>{gsap.registerPlugin(ScrollTrigger);const reduce=matchMedia("(prefers-reduced-motion:reduce)").matches;let lenis;if(!reduce&&window.Lenis){lenis=new Lenis({duration:1.1,smoothWheel:true,lerp:.08});lenis.on("scroll",ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0)}
const loader=document.querySelector(".loader"),prog=loader.querySelector(".loader-progress span"),num=loader.querySelector(".loader b");let n={v:0};gsap.to(n,{v:100,duration:1.5,ease:"power2.inOut",onUpdate:()=>num.textContent=String(Math.round(n.v)).padStart(2,"0")});gsap.to(prog,{width:"100%",duration:1.5,ease:"power2.inOut"});gsap.to(loader,{yPercent:-100,duration:.9,delay:1.65,ease:"power4.inOut",onComplete:()=>loader.remove()});
gsap.from(".hero-title span,.hero-title em,.hero-title strong",{y:80,opacity:0,duration:1,delay:2,stagger:.08,ease:"power4.out"});gsap.from(".hero-under,.hero-top",{y:25,opacity:0,duration:.7,delay:2.35,stagger:.1});
const cursor=document.querySelector(".cursor");if(matchMedia("(pointer:fine)").matches&&!reduce){let x=innerWidth/2,y=innerHeight/2,cx=x,cy=y;addEventListener("mousemove",e=>{x=e.clientX;y=e.clientY});gsap.ticker.add(()=>{cx+=(x-cx)*.18;cy+=(y-cy)*.18;gsap.set(cursor,{x:cx,y:cy})});document.querySelectorAll(".project a").forEach(e=>{e.onmouseenter=()=>cursor.classList.add("view");e.onmouseleave=()=>cursor.classList.remove("view")})}
const reveal=(els,vars={})=>gsap.utils.toArray(els).forEach(el=>gsap.from(el,{opacity:0,y:60,duration:.9,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 86%",once:true},...vars}));reveal(".intro-main,.stats div,.section-head,.services-head,.service,.pricing-grid,.test-head,.quote-grid article,.faq,.contact");
document.querySelectorAll(".reveal-img").forEach(el=>{gsap.to(el,{clipPath:"inset(0% 0% 0% 0%)",duration:1.1,ease:"power4.inOut",scrollTrigger:{trigger:el,start:"top 85%",once:true}})});
document.querySelectorAll(".project-image").forEach(el=>{gsap.from(el,{scale:.92,opacity:0,duration:1.1,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 85%",once:true}})});
document.querySelectorAll("[data-count]").forEach(el=>{let o={v:0},target=+el.dataset.count;ScrollTrigger.create({trigger:el,start:"top 85%",once:true,onEnter:()=>gsap.to(o,{v:target,duration:1.4,ease:"power2.out",onUpdate:()=>el.textContent=Math.round(o.v)})})});
if(!reduce){gsap.to(".art-card.card-one",{y:-35,rotation:7,scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:1}});gsap.to(".art-card.card-two",{y:50,rotation:-10,scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:1}})}
document.querySelectorAll(".service").forEach(s=>s.addEventListener("mouseenter",()=>{document.querySelectorAll(".service").forEach(x=>x.classList.remove("active"));s.classList.add("active")}));
const menu=document.querySelector(".mobile-menu");document.querySelector(".menu-toggle").onclick=()=>{const open=menu.classList.toggle("open");gsap.to(menu,{yPercent:open?0:-100,duration:.65,ease:"power4.inOut"});};document.querySelectorAll(".mobile-menu a").forEach(a=>a.onclick=()=>gsap.to(menu,{yPercent:-100,duration:.5}));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{let t=document.querySelector(a.getAttribute("href"));if(!t)return;e.preventDefault();lenis?lenis.scrollTo(t,{offset:-30}):t.scrollIntoView({behavior:"smooth"})}));
});
